<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UtilisateurSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Tous les mots de passe: password123
        DB::table('utilisateur')->insert([
            // Admin
            [
                'id' => 1,
                'nom' => 'Admin',
                'prenom' => 'System',
                'email' => 'admin@servicepro.com',
                'password' => Hash::make('password123'),
                'telephone' => '0612345678',
                'url' => null,
                'google_pw' => null,
                'address' => '123 Rue Principale, Casablanca',
                'avatar' => null,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Clients (ID 2-6)
            [
                'id' => 2,
                'nom' => 'Alami',
                'prenom' => 'Mohammed',
                'email' => 'mohammed.alami@example.com',
                'password' => Hash::make('password123'),
                'telephone' => '0623456789',
                'url' => null,
                'google_pw' => null,
                'address' => '45 Avenue Hassan II, Rabat',
                'avatar' => null,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'nom' => 'Benjelloun',
                'prenom' => 'Fatima',
                'email' => 'fatima.benjelloun@example.com',
                'password' => Hash::make('password123'),
                'telephone' => '0634567890',
                'url' => null,
                'google_pw' => null,
                'address' => '78 Boulevard Zerktouni, Casablanca',
                'avatar' => null,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'nom' => 'El Fassi',
                'prenom' => 'Karim',
                'email' => 'karim.elfassi@example.com',
                'password' => Hash::make('password123'),
                'telephone' => '0645678901',
                'url' => null,
                'google_pw' => null,
                'address' => '12 Rue de la Liberté, Marrakech',
                'avatar' => null,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'nom' => 'Idrissi',
                'prenom' => 'Leila',
                'email' => 'leila.idrissi@example.com',
                'password' => Hash::make('password123'),
                'telephone' => '0640123456',
                'url' => null,
                'google_pw' => null,
                'address' => '90 Rue Oued Fès, Rabat',
                'avatar' => null,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'nom' => 'Mansouri',
                'prenom' => 'Omar',
                'email' => 'omar.mansouri@example.com',
                'password' => Hash::make('password123'),
                'telephone' => '0641234567',
                'url' => null,
                'google_pw' => null,
                'address' => '15 Avenue Allal Ben Abdellah, Fes',
                'avatar' => null,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Intervenants (ID 7-15)
            [
                'id' => 7,
                'nom' => 'Tazi',
                'prenom' => 'Amina',
                'email' => 'amina.tazi@example.com',
                'password' => Hash::make('password123'),
                'telephone' => '0656789012',
                'url' => null,
                'google_pw' => null,
                'address' => '34 Avenue Mohammed V, Fes',
                'avatar' => null,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'nom' => 'Benslimane',
                'prenom' => 'Youssef',
                'email' => 'youssef.benslimane@example.com',
                'password' => Hash::make('password123'),
                'telephone' => '0667890123',
                'url' => null,
                'google_pw' => null,
                'address' => '56 Rue Ibn Battouta, Tanger',
                'avatar' => null,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'nom' => 'Chraibi',
                'prenom' => 'Sara',
                'email' => 'sara.chraibi@example.com',
                'password' => Hash::make('password123'),
                'telephone' => '0678901234',
                'url' => null,
                'google_pw' => null,
                'address' => '89 Boulevard Anfa, Casablanca',
                'avatar' => null,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'nom' => 'Radi',
                'prenom' => 'Hassan',
                'email' => 'hassan.radi@example.com',
                'password' => Hash::make('password123'),
                'telephone' => '0689012345',
                'url' => null,
                'google_pw' => null,
                'address' => '23 Avenue des FAR, Agadir',
                'avatar' => null,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'nom' => 'Bennani',
                'prenom' => 'Ahmed',
                'email' => 'ahmed.bennani@example.com',
                'password' => Hash::make('password123'),
                'telephone' => '0690123456',
                'url' => null,
                'google_pw' => null,
                'address' => '67 Rue Zerktouni, Casablanca',
                'avatar' => null,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'nom' => 'Alaoui',
                'prenom' => 'Khadija',
                'email' => 'khadija.alaoui@example.com',
                'password' => Hash::make('password123'),
                'telephone' => '0691234567',
                'url' => null,
                'google_pw' => null,
                'address' => '28 Avenue Mohammed VI, Rabat',
                'avatar' => null,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'nom' => 'Berrada',
                'prenom' => 'Mehdi',
                'email' => 'mehdi.berrada@example.com',
                'password' => Hash::make('password123'),
                'telephone' => '0692345678',
                'url' => null,
                'google_pw' => null,
                'address' => '45 Rue de France, Tanger',
                'avatar' => null,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'nom' => 'Fassi',
                'prenom' => 'Nadia',
                'email' => 'nadia.fassi@example.com',
                'password' => Hash::make('password123'),
                'telephone' => '0693456789',
                'url' => null,
                'google_pw' => null,
                'address' => '12 Boulevard Mohammed V, Marrakech',
                'avatar' => null,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'nom' => 'Lahlou',
                'prenom' => 'Samir',
                'email' => 'samir.lahlou@example.com',
                'password' => Hash::make('password123'),
                'telephone' => '0694567890',
                'url' => null,
                'google_pw' => null,
                'address' => '78 Avenue Hassan II, Agadir',
                'avatar' => null,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
